// SPDX-License-Identifier: MIT
#include "kad6/kad6_vep.h"
#include "kad6/kad6_bytes.h"

namespace kad6 {
namespace { const char kDomain[]="eSE-Kad6-VEP-v1"; }

Kad6Status K6VepSerializeSigned(const K6VirtualIdentityEndpoint&v,std::vector<Byte>&out){out.clear();if(v.apparent_tcp_port==0||v.source_lease_id==0||v.valid_until==0)return Kad6Status::BadValue;std::vector<Byte>a;Kad6Status s=EncodeKad6Address(v.apparent_source_ip,a);if(s!=Kad6Status::Ok)return s;ByteWriter w(out);w.bytes(reinterpret_cast<const Byte*>(kDomain),sizeof(kDomain)-1);w.u8(1);w.bytes(a.data(),a.size());w.u16le(v.apparent_tcp_port);w.u16le(v.apparent_udp_port);w.bytes(v.exit_node_pub.data(),32);w.u64le(v.source_lease_id);w.u64le(v.valid_until);return Kad6Status::Ok;}
Kad6Status SignK6Vep(const Kad6CryptoHooks&h,K6VirtualIdentityEndpoint&v,std::vector<Byte>&out){std::vector<Byte>signedBytes;Kad6Status s=K6VepSerializeSigned(v,signedBytes);if(s!=Kad6Status::Ok)return s;if(!h.ed25519_sign||!h.ed25519_sign(nullptr,0,signedBytes.data(),signedBytes.size(),v.signature.data()))return Kad6Status::AuthFailed;return EncodeK6Vep(v,out);}
Kad6Status EncodeK6Vep(const K6VirtualIdentityEndpoint&v,std::vector<Byte>&out){out.clear();std::vector<Byte>tmp;Kad6Status s=K6VepSerializeSigned(v,tmp);if(s!=Kad6Status::Ok)return s;std::vector<Byte>a;s=EncodeKad6Address(v.apparent_source_ip,a);if(s!=Kad6Status::Ok)return s;ByteWriter w(out);w.u8(1);w.bytes(a.data(),a.size());w.u16le(v.apparent_tcp_port);w.u16le(v.apparent_udp_port);w.bytes(v.exit_node_pub.data(),32);w.u64le(v.source_lease_id);w.u64le(v.valid_until);w.bytes(v.signature.data(),64);return Kad6Status::Ok;}
Kad6Status DecodeK6Vep(const Byte*in,std::size_t len,K6VirtualIdentityEndpoint&out,std::size_t*consumed)noexcept{out={};if(consumed)*consumed=0;if(!in&&len)return Kad6Status::NullArgument;ByteReader r(in,len);const Byte version=r.u8();if(!r.ok())return Kad6Status::Truncated;if(version!=1)return Kad6Status::UnsupportedVersion;std::size_t n=0;Kad6Status s=DecodeKad6Address(in+r.pos(),r.remaining(),out.apparent_source_ip,&n);if(s!=Kad6Status::Ok){out={};return s;}r.take(n);out.apparent_tcp_port=r.u16le();out.apparent_udp_port=r.u16le();r.bytes(out.exit_node_pub.data(),32);out.source_lease_id=r.u64le();out.valid_until=r.u64le();r.bytes(out.signature.data(),64);if(!r.ok()){out={};return Kad6Status::Truncated;}if(r.pos()!=len){out={};return Kad6Status::Malformed;}if(!out.apparent_tcp_port||!out.source_lease_id||!out.valid_until){out={};return Kad6Status::BadValue;}if(consumed)*consumed=len;return Kad6Status::Ok;}
Kad6Status VerifyK6Vep(const Kad6CryptoHooks&h,const K6VirtualIdentityEndpoint&v,std::uint64_t now)noexcept{if(v.valid_until<=now)return Kad6Status::Expired;if(v.valid_until-now>kK6VepMaxTtlSeconds)return Kad6Status::BadValue;std::vector<Byte>b;if(K6VepSerializeSigned(v,b)!=Kad6Status::Ok)return Kad6Status::BadValue;if(!h.ed25519_verify||!h.ed25519_verify(v.exit_node_pub.data(),b.data(),b.size(),v.signature.data()))return Kad6Status::AuthFailed;return Kad6Status::Ok;}
} // namespace kad6
