// this file is part of eMule eSE — Live channel identity (F2)
//
// Channel = Ed25519 keypair. Owner signs ChannelRecord; channel_id = pubkey.
// Public records are serialised plaintext; private records are AEAD-sealed
// with a key derived from the channel secret (Cap 5 §5.3 thesis).
//
// Wire format spec: docs/thesis/05-protocol-architecture.md §5.2.2.
#pragma once

#include <vector>

namespace eSELive {

// === ChannelKey ==========================================================

struct ChannelKey {
    uint8_t pubkey[32];   // Ed25519 public, == channel_id
    uint8_t secret[32];   // Ed25519 private, NEVER serialised in plaintext
};

// Generate a new channel keypair. Returns true on success.
bool ChannelKeyGenerate(ChannelKey& outKey);

// === ChannelRecord ======================================================
// Serialised layout (see §5.2.2 thesis):
//   version           uint8  = 1
//   channel_pubkey    [32]
//   seq               uint32 LE  (monotonic; >prev to invalidate)
//   timestamp_unix    uint64 LE  (±2 h slack vs receiver clock)
//   name              uint8 lenN + N bytes UTF-8 (N <= 64)
//   description       uint16 lenD LE + D bytes UTF-8 (D <= 256)
//   category          uint8 enum {1..6}
//   language          [2]   ISO 639-1 ("es","en",...,"  ")
//   icon_md4          [16]
//   access_mode       uint8  (0=public, 1=private)
//   flags             uint8  (bit0 high-risk, bit1 nsfw, bit2 unlisted)
//   rendezvous        uint8 count + count*(type1+addrLen1+addr+port2+prio1)
//   successor         uint8 hasSucc + (hasSucc ? [32] : 0)
//   signature         [64]  Ed25519 over all the above

struct RendezvousEntry {
    uint8_t type;        // 1=onion 2=tailnet 3=clearnet4 4=clearnet6
    uint16_t port;
    uint8_t priority;
    CStringA addr;       // <= 64 bytes
};

struct ChannelRecord {
    uint8_t version;
    uint8_t channel_pubkey[32];
    uint32_t seq;
    uint64_t timestamp_unix;
    CStringA name;            // UTF-8
    CStringA description;     // UTF-8
    uint8_t category;
    char language[2];
    uint8_t icon_md4[16];
    uint8_t access_mode;
    uint8_t flags;
    std::vector<RendezvousEntry> rendezvous;
    bool has_successor;
    uint8_t successor[32];
    uint8_t signature[64];

    ChannelRecord();
};

// Build canonical bytes that the signature covers (all fields except the
// signature itself). Used by both signer and verifier so they hash the
// same bytes. Returns the serialised body in `out`.
bool ChannelRecordSerializeBody(const ChannelRecord& r, std::vector<uint8_t>& out);

// Full wire-format serialisation (body + signature appended).
bool ChannelRecordSerialize(const ChannelRecord& r, std::vector<uint8_t>& out);

// Parse a wire-format record. Returns false on malformed input.
bool ChannelRecordParse(const uint8_t* in, size_t inLen, ChannelRecord& outRec);

// Sign with the channel's private Ed25519 key. Writes the 64-byte sig
// into rec.signature. Returns true on success.
bool ChannelRecordSign(ChannelRecord& rec, const uint8_t secret[32]);

// Verify rec.signature against rec.channel_pubkey. Returns true iff valid.
bool ChannelRecordVerify(const ChannelRecord& rec);

// === Sealed records (private channels) ===================================
// For access_mode=1, the wire-published body is the Kad key:
//   K_kad_lookup = SHA1("ese.live.priv." || HMAC-SHA256(channel_pubkey, hour))
// And the Kad value is:
//   AEAD-Encrypt(K_kad = HKDF(channel_secret, "kad-record-key-v1"),
//                nonce_random_12,
//                aad = empty,
//                plaintext = ChannelRecordSerialize)
//
// Caller computes the Kad lookup key separately (LiveChannel doesn't talk
// to Kad). LiveChannel only seals and opens the body.

// Seal a record body (already serialised) under K_kad derived from secret.
// `nonceOut` (12 B) is generated by this function. `outCipher` receives
// body+16-byte tag. Returns true on success.
bool ChannelRecordSeal(const std::vector<uint8_t>& bodySerialised,
                       const uint8_t secret[32],
                       uint8_t nonceOut[12],
                       std::vector<uint8_t>& outCipher);

// Open a sealed record. Returns true iff AEAD verifies.
bool ChannelRecordOpen(const uint8_t* cipher, size_t cipherLen,
                       const uint8_t nonce[12],
                       const uint8_t secret[32],
                       std::vector<uint8_t>& outBody);

}  // namespace eSELive
